### ISSUE TITLE
Container ignore PGID and PUID

### ISSUE THREAD

**Issue by StephanFastxl** [rogerfar/rdt-client#214]
I use the latetst rdtclient in docker and the new version of rdt-client ignores the PGID and PUID, the files and folders are now 911 instead of my given 1000

**Comment by rogerfar** [comment]
I'm not sure what could cause that as I'm not a Docker wizard at all.

@ravensorb do you have an idea?

**Comment by ravensorb** [comment]
Good question -- I noticed when watchdog pulled down the latest build rdtclient starting having permission issues as well.  Let me see if I can figure out what changed (possibly something in the base linuxserver.io image that we need to account for).

**Comment by Micsters** [comment]
Still having this issue dockers, for some reason it keeps setting the Group to 911 on all files/folders in the downloads dirs on updates or restarts. Have to and change em back to 1000 for it load up again.

**Comment by BlackMamba248** [comment]
I'm also having the same issue I believe. Recently set it up and having permission issues with sonarr being unable to import and rename. How did you check the group value and then set it back to 1000?

**Comment by Micsters** [comment]
> I'm also having the same issue I believe. Recently set it up and having permission issues with sonarr being unable to import and rename. How did you check the group value and then set it back to 1000?

Not sure your setup, but with mine I run it on a PI4 with Docker/Portainer. I SSH into my system, went one level above my download dir that I have it set to, and did a ls -l and saw that all my files/dir have changed to 911 owner/group,  So i did a "sudo chgrp -R 1000 YourDownloadDir"  That will change the group for all files/dirs in the downloads dir to group 1000.   You may also have to change the owner to 1000 as well with the "sudo chown -R 1000 YourDownloadDir"

**Comment by BlackMamba248** [comment]
Oh I see. I'm on unraid for my setup. Hmm after changing the folder and file values back to 1000, does that also fix it for any new files/folders created when rdt downloads new stuff? Also, are you using rdt with sonnarr/radarr?

**Comment by Micsters** [comment]
Yes, it will correct the issue and all the file permissions will be fine on any new downloads until the next time you go to update or recreate the docker for RDT-Client.

**Comment by BlackMamba248** [comment]
Ah interesting, I thought that would be the case too. Just did it for unraid but seems the issue still persists. The rdt client will keep the value until you restart the client. However, it seems any new files it creates reverts back to the incorrect permissions due to incorrect UMASK I think?

**Comment by BlackMamba248** [comment]
Another question, does rdt-client download your file into a folder named the same as the file? Was wondering if that was an issue as qbittorrent gives the option to download the file by itself without creating a folder to put it in. The folder it creates for me so far has the incorrect permissions, not sure about the actual file inside since can't go into that directory to check in the unraind terminal due to folder name being too long

**Comment by Micsters** [comment]
@BlackMamba248  Now that I have manually set all the permissions of the files/folders in my download folder, it's working like it should. It does make new folders and sets em to the correct permissions. I'm sure I will have issues again once I recreated the container again with the next update.  But at least i know how to fix it now.

After first having issues I completely removed the container and volumes, and did a fresh install and this time I did set the PGID/PUID in my docker compose. Not sure if you did that or not. but mine looks like this.. 

version: '3.3'
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /portainer/Files/AppData/Config/rdtc:/data/db
      - /portainer/downloads/rdtclient:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped

**Comment by ravensorb** [comment]
Just submitted a PR #221 which should take care of the issue.

**Comment by rogerfar** [comment]
I published 2.0.23 on Docker now, let me know if this fixes it.

**Comment by ctriaan** [comment]
It didn't fix mine.

It doesn't seem to start, but there are no errors.

rdtclient      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
rdtclient      | [s6-init] ensuring user provided files have correct perms...exited 0.
rdtclient      | [fix-attrs.d] applying ownership & permissions fixes...
rdtclient      | [fix-attrs.d] done.
rdtclient      | [cont-init.d] executing container initialization scripts...
rdtclient      | [cont-init.d] 01-envfile: executing...
rdtclient      | [cont-init.d] 01-envfile: exited 0.
rdtclient      | [cont-init.d] 01-migrations: executing...
rdtclient      | [migrations] started
rdtclient      | [migrations] no migrations found
rdtclient      | [cont-init.d] 01-migrations: exited 0.
rdtclient      | [cont-init.d] 02-tamper-check: executing...
rdtclient      | [cont-init.d] 02-tamper-check: exited 0.
rdtclient      | [cont-init.d] 10-adduser: executing...
rdtclient      |
rdtclient      | -------------------------------------
rdtclient      |           _         ()
rdtclient      |          | |  ___   _    __
rdtclient      |          | | / __| | |  /  \
rdtclient      |          | | \__ \ | | | () |
rdtclient      |          |_| |___/ |_|  \__/
rdtclient      |
rdtclient      |
rdtclient      | Brought to you by linuxserver.io
rdtclient      | -------------------------------------
rdtclient      |
rdtclient      | To support LSIO projects visit:
rdtclient      | https://www.linuxserver.io/donate/
rdtclient      | -------------------------------------
rdtclient      | GID/UID
rdtclient      | -------------------------------------
rdtclient      |
rdtclient      | User uid:    1000
rdtclient      | User gid:    1000
rdtclient      | -------------------------------------
rdtclient      |
rdtclient      | [cont-init.d] 10-adduser: exited 0.
rdtclient      | [cont-init.d] 90-custom-folders: executing...
rdtclient      | [cont-init.d] 90-custom-folders: exited 0.
rdtclient      | [cont-init.d] 99-custom-scripts: executing...
rdtclient      | [custom-init] no custom files found exiting...
rdtclient      | [cont-init.d] 99-custom-scripts: exited 0.
rdtclient      | [cont-init.d] done.
rdtclient      | [services.d] starting services
rdtclient      | [services.d] done.

**Comment by ravensorb** [comment]
Ca you share your docker-compose or docker run (and env file if there is one)?

**Comment by ctriaan** [comment]
rdtclient:  #Real-debrid download client
    container_name: rdtclient
    image: rogerfar/rdtclient:2.0.23        #2.0.19
    profiles:
      - more
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
#      - D:/Downloads/:/data/downloads
      - /media/Seagate/downloads/complete:/downloads
#      - D:/Docker/rdt-client/:/data/db
      - ./data/config/rdt-client/:/data/db
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 6500:6500

**Comment by ravensorb** [comment]
The compose file is setting PUID and PGID to 1000 and that is what the container is showing when it starts up.  Can you explain more on what is not working?

**Comment by ctriaan** [comment]
Here's a screenshot. My commented lines mase the previous one look strange

![image](https://user-images.githubusercontent.com/127965759/225348752-69261e4b-01ed-43aa-adf8-4ca9ef1fca71.png)

**Comment by Micsters** [comment]
Just updated mine. Getting same thing as ctriaan.. Unable to connect to it. No errors in log,

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by ctriaan** [comment]
Version 2.0.19 works

rdtclient      | [custom-init] No custom services found, skipping...
rdtclient      | s6-rc: info: service s6rc-oneshot-runner: starting
rdtclient      | s6-rc: info: service s6rc-oneshot-runner successfully started
rdtclient      | s6-rc: info: service fix-attrs: starting
rdtclient      | s6-rc: info: service 00-legacy: starting
rdtclient      | s6-rc: info: service 00-legacy successfully started
rdtclient      | s6-rc: info: service fix-attrs successfully started
rdtclient      | s6-rc: info: service legacy-cont-init: starting
rdtclient      | cont-init: info: running /etc/cont-init.d/01-envfile
rdtclient      | cont-init: info: /etc/cont-init.d/01-envfile exited 0
rdtclient      | cont-init: info: running /etc/cont-init.d/01-migrations
rdtclient      | [migrations] started
rdtclient      | [migrations] no migrations found
rdtclient      | cont-init: info: /etc/cont-init.d/01-migrations exited 0
rdtclient      | cont-init: info: running /etc/cont-init.d/10-adduser
rdtclient      | usermod: no changes
rdtclient      |
rdtclient      | -------------------------------------
rdtclient      |           _         ()
rdtclient      |          | |  ___   _    __
rdtclient      |          | | / __| | |  /  \
rdtclient      |          | | \__ \ | | | () |
rdtclient      |          |_| |___/ |_|  \__/
rdtclient      |
rdtclient      |
rdtclient      | cont-init: info: running /etc/cont-init.d/30-config
rdtclient      | cont-init: info: running /etc/cont-init.d/30-config
rdtclient      | Setting permissions
rdtclient      | cont-init: info: /etc/cont-init.d/30-config exited 0
rdtclient      | cont-init: info: running /etc/cont-init.d/99-custom-files
rdtclient      | [custom-init] No custom files found, skipping...
rdtclient      | cont-init: info: /etc/cont-init.d/99-custom-files exited 0
rdtclient      | s6-rc: info: service legacy-cont-init successfully started
rdtclient      | s6-rc: info: service init-mods: starting
rdtclient      | s6-rc: info: service init-mods successfully started
rdtclient      | s6-rc: info: service init-mods-package-install: starting
rdtclient      | s6-rc: info: service init-mods-package-install successfully started
rdtclient      | s6-rc: info: service init-mods-end: starting
rdtclient      | s6-rc: info: service init-mods-end successfully started
rdtclient      | s6-rc: info: service init-services: starting
rdtclient      | s6-rc: info: service init-services successfully started
rdtclient      | s6-rc: info: service legacy-services: starting
rdtclient      | services-up: info: copying legacy longrun rdtclient (no readiness notification)
rdtclient      | s6-rc: info: service legacy-services successfully started
rdtclient      | s6-rc: info: service 99-ci-service-check: starting
rdtclient      | [ls.io-init] done.
rdtclient      | s6-rc: info: service 99-ci-service-check successfully started
rdtclient      | Changing to /app folder
rdtclient      | Starting rtdclient
rdtclient      | [15:21:36 WRN] Using an in-memory repository. Keys will not be persisted to storage.
rdtclient      | [15:21:36 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
rdtclient      | [15:21:36 WRN] No XML encryptor configured. Key {4659ab44-3a5a-484c-abae-b9bb8763b52d} may be persisted to storage in unencrypted form.
rdtclient      | [15:21:36 WRN] Starting host on version 2.0.19.0

**Comment by ravensorb** [comment]
I just added a healthcheck on my local copy

```
 healthcheck:
      test: curl --fail http://localhost:6500 || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s
```

and it comes up heathy.  Can you try the same?

**Comment by Micsters** [comment]
Im not sure how to do a healthcheck... But i logged into the running container and did a curl
```
root@17ad0755c86f:/app# curl --fail http://localhost:6500
curl: (7) Failed to connect to localhost port 6500: Connection refused
```

**Comment by ravensorb** [comment]
For info here is my dokcker-compose.yml file

```
version: '3.3'

services:
    rdtclient:
        image: rogerfar/rdtclient
        container_name: rdtclient
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PUID=1001
            - PGID=1001
        volumes:
            - ${PWD}/data/downloads:/data/downloads
            - ${PWD}/data/db:/data/db
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'
        healthcheck:
            test: curl --fail http://localhost:6500 || exit 1
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 30s
```
then when you run ```docker ps`` you should see something like this:
```
b3e980fe5f25   rogerfar/rdtclient                       "/init"                  3 minutes ago   Up 3 minutes (healthy)   0.0.0.0:6500->6500/tcp, :::6500->6500/tcp
```
Now that said, when I build it locally it runs and starts correctly.  If I pull the one on docker hub it looks like the rdtclient app is not actually starting.  Looking into it now.

**Comment by ctriaan** [comment]
I also thought it was only setting permissions and not actually starting.

docker top rdtclient gives me this:
![image](https://user-images.githubusercontent.com/127965759/225369619-b18ce29a-7d46-4dda-af37-00e943fc8afa.png)

and 2.0.19:
![image](https://user-images.githubusercontent.com/127965759/225370125-bef373c6-5985-45f3-ab2d-d35b49a51950.png)

**Comment by Micsters** [comment]
My docker ps with healthcheck:
```
4714e3cba2a1   rogerfar/rdtclient:latest                 "/init"                  3 minutes ago   Up 3 minutes (unhealthy)   0.0.0.0:6500->6500/tcp, :::6500->6500/tcp                                                                                                                rdtclient
```

**Comment by ravensorb** [comment]
Ok, I think I found the issue -- looks like there is a bug in the current ubuntu image from linuxserver.io that is preventing the service from starting correctly. I have an updated build that is based on alpine (bonus is the image size is smaller).  @Micsters  @ctriaan would you be open to giving this image a try -- ```ravensorb/rdtclient```  (its for amd64 only right now)

[Link to Docker Hub](https://hub.docker.com/r/ravensorb/rdtclient)

**Comment by ctriaan** [comment]
@ravensorb, it's working.

**Comment by Micsters** [comment]
I will try it when ARM64 is out.

**Comment by ravensorb** [comment]
Just pushed PR #224

**Comment by Micsters** [comment]
Thank you all for fixing the issues, you all are Awesome! Love it when people come together!

**Comment by rogerfar** [comment]
@Micsters can you verify if the latest tag works?

**Comment by Micsters** [comment]
@rogerfar Just tried it, Im getting this --
s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

Im on ARM64, with Docker/Portainer

Saw others getting it as well..

**Comment by ravensorb** [comment]
@Micsters can you provide more details on how you are running it?

**Comment by sylvaindd** [comment]
Same error running on Docker amd64 :
> s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

**Comment by ravensorb** [comment]
@StephanFastxl  can you try running the one I pushed -- ``ravensorb/rdtclient```

**Comment by goldenpipes** [comment]
> Ok, I think I found the issue -- looks like there is a bug in the current ubuntu image from linuxserver.io that is preventing the service from starting correctly. I have an updated build that is based on alpine (bonus is the image size is smaller). @Micsters @ctriaan would you be open to giving this image a try -- `ravensorb/rdtclient` (its for amd64 only right now)
> 
> [Link to Docker Hub](https://hub.docker.com/r/ravensorb/rdtclient)

Alpine > Ubuntu. thanks!

**Comment by jake8923948** [comment]
> @StephanFastxl can you try running the one I pushed -- `ravensorb/rdtclient`

forgive me for jumping in, 
I don't have much to offer in terms of diagnostics and whatever, i'm a complete docker/linux noob. However,
I was on 2.0.19 and EVERYTHING worked fine. 
Debian 11 running docker'd: radarr, sonarr, prowlarr, whisparr, stash, jellyfin and rdt-client (and some other unrelated dockers). 
Only issue, my server was running out of memory running everything. I upgraded my server (more ram, more storage) and to top it off, tried OMV6 just because.

This is where the issues arose. I kept getting permission errors... user abc, u:911/g:911 were owners, and couldn't read or write etcetc. Obviously, now i've pulled the latest, I kept getting this s6-rc-compile cyclic service error. I've then come across these threads.. 
Roger's image showed unhealthy on portainer with that error and nothing was showing on 6500, your image is showing the login/account creation page and portainer shows healthy
But yes, after 2.019 I was getting user/group 911 as owner of anything downloaded which caused issues with radarr/sonarr/bazarr etc. 

I spent 7 hours yesterday reinstalling omv5 and 6, centos stream 9, ubuntu server, proxmox, debian and all had this issue. I've tried hotio images etc but i'm glad the issue has been caught and hopefully resolved. Thank you both for your hard work ! :D

**Comment by jake8923948** [comment]
unfortunately, your image "ravensorb/rdtclient:latest" (version v2.0.23) is still downloading/saving as 911
![image](https://user-images.githubusercontent.com/25887548/225808988-644362f0-a3b5-4c41-a112-3f5015c3098f.png)

and there's no user or group 911 on the system, so definitely an image issue. Going to manually try 0.19 again and report back

**Comment by ctriaan** [comment]
@jake8923948 try using
environment:
- PUID=1000
- PGID=1000

**Comment by ctriaan** [comment]
I am also getting this on version 2.0.24:
rdtclient      | s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

ravensorb/rdtclient works, but the new downloader is extremely slow and just stops working after two or three files when I download a complete season with sonarr. Are there settings that I should change, coming from Simple Downloader?
It also took 20 minutes to unpack a 1.9 GB rar file.

**Comment by ravensorb** [comment]
I just pushed a new build that has full mulit-arch (arm and x86) support under my account on docker hub -- ```ravensorb/rdtclient``` 

Can you give that a try?

**Comment by Micsters** [comment]
@ravensorb 

Works here! ARM64

**Comment by ctriaan** [comment]
> @ctriaan can you verify if the docker container works and if permissions are being set correctly on the ravensorb/rdtclient image?

@rogerfar it works, but downloading a complete series with sonarr is not working correctly. 

I've just tested it on a 10 episode season (after changing parallel downloads to 100 instead of 3) and it got stuck on "Downloading file 10/10 (100.00% - 77.8 MB/s)". If I look at the detail, all 10 downloads show 100%, but they all show "not finished yet".

From my post above:
> * The new downloader is extremely slow and just stops working after two or three files when I download a complete season with sonarr.
> * With a season as a rar file, Internal Downloader took 20 minutes to unpack 1.9 GB.
> 
> Are there settings that I should change, coming from Simple Downloader?

**Comment by rogerfar** [comment]
Yeah I saw that, but lets keep the issues separate. At this point I just want to make sure the image it actually working.

**Comment by ctriaan** [comment]
@rogerfar , no problem.

I wasn't sure if it was a separate issue because it was the first version that worked for me after 2.0.19, which didn't have the problem.

**Comment by jake8923948** [comment]
> @jake8923948 try using environment:
> 
>     * PUID=1000
> 
>     * PGID=1000

Legend! Thanks! 
Not sure how i missed this lol.. ran everything else as 1000:1000 but rdt client

**Comment by jake8923948** [comment]
> @jake8923948 Also you might want to take a look thru all your files/folders in your downloads folder and make sure they all set to 1000, you might find a few of them that we changed set to 911

Hi, thanks
I recursively chownd the directory after passing the env variables

Thanks though!

**Comment by ravensorb** [comment]
@rogerfar - think we are good for another PR with the tweaks?

**Comment by BlackMamba248** [comment]
I agree with Micsters above, appreciate everyone spending the time to troubleshoot and fix so quickly. Was going crazy trying to figure out the permission stuff prior to finding the issues here. 

I'm on unraid and didn't try any of the new versions yet to fix but one weird thing I wanted to note was that the rdt-client 
 pulled from docker hub installed area for even 2.0.19 still listed PUID and PGID as 911 in the logs. I also tried to add the variables to set the PUID and PGID correctly in the template setting and it had no affect even temporarily. I'm new to all this so might be doing something wrong but wanted to see if it was a related issue to what is currently on.

I deleted the docker up and tried to install via docker compose with reference to a layout mentioned above with stating the environmental variables on 2.0.19 version and that seemed to fix the permission issues and made it stick. Not sure if there was any differences in installing via docker compose vs pulling from the docker hub for the permissions issue.

**Comment by ravensorb** [comment]
@rogerfar  - I am testing one more thing and then I'll submit the PR.

Two other questions
* Mind if I make a change to the Dockerfile to use the local files (via a COPY) instead of doing a git pull during the build?
* Thinking about creating a powershell script that will make it easier to build and run the multi-arch builds.  Any interest in me adding that?
* Working on a Github Action that will do a full build and push to docker hub (or ghcr).  Interested in me adding this as well?

**Comment by rogerfar** [comment]
Yes please! I was thinking of using GH Actions instead of building locally all the time.

**Comment by BlackMamba248** [comment]
> different issue here

@Joshua-18 Dang, glad I'm not the only one racking my brain trying to figure it out haha. Does the log for the rdt-client show the correct 99 and 100 PGID and PUID settings after you added it in the tmeplate? What version are you using with those added settings? 

I have tried adding the PGID and PUID as variables in the add option at the bottom of the temple from the docker hub route but have found that the PGID and PUID still lists 911 in the logs after install.

**Comment by rogerfar** [comment]
2.0.25 is now published, that should fix the issue again.

**Comment by kloe7** [comment]
[15:39:28 WRN] Starting host on version 2.0.25.0
[15:39:30 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Setting permissions
Changing to /app folder
Starting rtdclient
[15:39:31 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[15:39:32 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[15:39:32 WRN] No XML encryptor configured. Key {cd7fce5e-bffe-4e8d-b8a9-b74c5bf8b3d5} may be persisted to storage in unencrypted form.
[15:39:32 WRN] Starting host on version 2.0.25.0
[15:39:34 ERR] BackgroundService failed

I get to Starting host on version 2.0.25.0 then it just gets stuck in that loop and repeats until I kill it. Reverted back to 2.0.19 for now.

**Comment by ctriaan** [comment]
@rogerfar and @ravensorb , thank you for all the hard work. 2.0.25 works for me.

I still do have the other issue where it is a lot slower than 2.0.19 - probably because of the change in downloader.

**Comment by janaxhell** [comment]
> I still do have the other issue where it is a lot slower than 2.0.19 - probably because of the change in downloader.

Ah, that's an issue I got too, 2 nights ago my server crashed and with Grafana I could clearly see that RDTclient hogged the system for several hours, I think I was trying ravensorb build.

**Comment by ravensorb** [comment]
> Yes please! I was thinking of using GH Actions instead of building locally all the time.

Ok, it should be in the PR -- it is set to only build when a new tag is added (has to start with v) and it requires 2 secrets to be configured (docker login and token).  It also has the ability to push to the github container registry if you want.  Let me know if that works.

**Comment by ctriaan** [comment]
> @rogerfar and @ravensorb , thank you for all the hard work. 2.0.25 works for me.
> 
> I still do have the other issue where it is a lot slower than 2.0.19 - probably because of the change in downloader.

@rogerfar , thank you. Version 2.0.26 fixed my speed issue.

**Comment by yunyunls** [comment]
Hello,

I am having this problem that the container is ignoring the PGID and PUID and gives the files it downloads permissions from user 911. 

I am on version 2.0.30 and running the program through unraid. Has anyone manage to fix this?

**Comment by jake8923948** [comment]
> Hello,
> 
> I am having this problem that the container is ignoring the PGID and PUID and gives the files it downloads permissions from user 911.
> 
> I am on version 2.0.30 and running the program through unraid. Has anyone manage to fix this?

Docker is docker, regardless where its installed I believe?
You have to pass the env variables PGID/PUID of the user you want to run the container as (the same user as other containers is best.)
So find out your user and group ID, then pass this to the container
PGID = xyz
PUID = xyz

**Comment by yunyunls** [comment]
> > Hello,
> > I am having this problem that the container is ignoring the PGID and PUID and gives the files it downloads permissions from user 911.
> > I am on version 2.0.30 and running the program through unraid. Has anyone manage to fix this?
> 
> Docker is docker, regardless where its installed I believe? You have to pass the env variables PGID/PUID of the user you want to run the container as (the same user as other containers is best.) So find out your user and group ID, then pass this to the container PGID = xyz PUID = xyz


Thank you for the reply.

I have already passed the appropriate environmental variables to the container using the same user snd group as all my other containers and as I said the rdt-client container ignores it. I already tried uninstalling and doing a fresh install of the container to no success.

**Comment by ravensorb** [comment]
Can you share your compose fie (or your docker run command) and any related .env files?

**Comment by yunyunls** [comment]
I am using unraid so this is the docker run command that unraid uses for the docker `/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='rdtclient' --net='anix' -e TZ="Asia/Tokyo" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="rdtclient" -e 'Community_Applications_Conversion'='true' -e 'language'='en_US.UFT-8' -e ' PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:6500]' -p '6500:6500/tcp' -v '/mnt/user/media/downloads/':'/downloads':'rw,shared' -v '/mnt/user/appdata/rdtclient':'/config':'rw' -v '/mnt/user/appdata/rdtclient':'/data/db':'rw' 'rogerfar/rdtclient' `

I am not sure if maybe I am missing some sort of other environmental variable that I need to pass to the container.

**Comment by ravensorb** [comment]
Three quick things jump out at me 
- I don't think you need to wrap the env names and values in single quotes
- There is a space between the single quote and PUID which would cause an issue (if you remove the single quotes based on the above statement you would fix this)
- You are mixing single quotes and double quotes (just a little odd as they mean different things to the shell)
```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create \
       --name=rdtclient \
       --net=anix \
       -e TZ="Asia/Tokyo" \
       -e HOST_OS="Unraid" \
       -e HOST_HOSTNAME="Tower" \
       -e HOST_CONTAINERNAME="rdtclient" \
       -e Community_Applications_Conversion="true" \
       -e language="en_US.UFT-8" \
       -e PUID="99" \
       -e PGID="100" \
       -e UMASK="022" \
       -l net.unraid.docker.managed="dockerman" \
       -l net.unraid.docker.webui="http://[IP]:[PORT:6500]" \
       -p "6500:6500/tcp" \
       -v /mnt/user/media/downloads/:/downloads:rw,shared \
       -v /mnt/user/appdata/rdtclient:/config:rw \
       -v /mnt/user/appdata/rdtclient:/data/db:rw rogerfar/rdtclient
```

**Comment by rogerfar** [comment]
I'm going to say that this is fixed now as it's pretty much in line with other *arr containers.
