### ISSUE TITLE
s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

### ISSUE THREAD

**Issue by kloe7** [rogerfar/rdt-client#228]
C:\>docker run --restart unless-stopped --pull=always --volume D:/media:/data/downloads --volume C:/docker/rdt-client:/data/db --log-driver json-file --log-opt max-size=10m -p 6500:6500 --name rdtclient rogerfar/rdtclient:latest
latest: Pulling from rogerfar/rdtclient
6f0fdad1ce92: Pull complete
c61fe2056171: Pull complete
604d992cfe46: Pull complete
e4bccb8e029e: Pull complete
17a07048057f: Pull complete
4f4fb700ef54: Pull complete
723b766183e1: Pull complete
277ce57e9b7a: Pull complete
062ead4436bb: Pull complete
Digest: sha256:40658d5b7d26ac6cdee9cb88e5378f6e851f458ef1e38a4cad8a7291a4c24682
Status: Downloaded newer image for rogerfar/rdtclient:latest
s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

I'm using Windows 10. Have to keep reverting back to v2.0.19. every update since then has failed for me.

**Comment by Micsters** [comment]
They are working on it.. Give em a little time -- See this issue #214 to be updated on it.

**Comment by fgurdradee** [comment]
Thanks . Reverting to image: rogerfar/rdtclient:2.0.19 for the interim. 

@rogerfar and other devs thanks for your work on this project.

**Comment by fgurdradee** [comment]
Just had a thought. Is there a way to create a new image tag "stable" that a is a few releases behind latest?
e.g.
image: rogerfar/rdtclient:stable

**Comment by Micsters** [comment]
@fgurdradee 2.0.25 should be working for ya.   

As for updating, it's best to always give any new release of any type of software a few days to see if there is any issues before updating to it.  As for stable tag, that is up to @rogerfar

**Comment by MagmaMDK** [comment]
On my side ( docker on synology) 2.0.25 is still not ok with same error
s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services

So I keep running with 2.0.19 for now

**Comment by Micsters** [comment]
@MagmaMDK Try Ravens Orbs image and see if that works for ya.. Thats what Im using and it works, tho it comes up as version .23 but should be same as .25  -- ravensorb/rdtclient:latest

**Comment by fgurdradee** [comment]
@Micsters 2.0.25 not working here docker on ubuntu server. still on 2.0.19. will monitor that [issue 214 ](https://github.com/rogerfar/rdt-client/issues/214)

**Comment by rogerfar** [comment]
2.0.25 is now published. If you still experience the same issues, please keep it central in #214.
