### ISSUE TITLE
Download stuck

### ISSUE THREAD

**Issue by Elrau** [rogerfar/rdt-client#420]
**What version are you using?**
2.0.61

**Wat OS are you running?**
Debian

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Alldebrid

**Which downloader are you using?**
Internal Downloader

Hello,

I don't understand why my download are stuck. Perhaps someone will have an idea.
I use the default configuration with Internal Downloader but everytime, at a random moment at the beginning, download get stuck like this :

![image](https://github.com/rogerfar/rdt-client/assets/3164896/d89debe1-547f-4e18-a233-fe7d5c72f140)

In debug log, only "Processing for torrent xxxxx. Waiting for downloads to complete" with the same perce,tage as in the IHM.
I dont understand what am I doing wrong.

**Comment by rogerfar** [comment]
Mine started showing the same symptoms last night, I'll have a look later today.

**Comment by rogerfar** [comment]
I pushed version 2.0.62, will take a bit to finish building, but should've fixed this issue.

**Comment by Elrau** [comment]
Thanks for the fix unfortunately I still have the same behavior after upgrading to 2.0.62. Perhaps it's because of Alldebrid instead of Realdebrid ?
I tried to switch to Bezzad but speed is incredibly slow on this one when I was full speed with Internal

If you need more information or test I can do some

**Comment by rogerfar** [comment]
Can you post a log?

**Comment by Elrau** [comment]
Staring container + request :

```
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____
      | __  |  |  | |  |  |    \
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Setting permissions
[custom-init] No custom files found, skipping...
Setting permissions
Changing to /app folder
Starting rtdclient
[ls.io-init] done.
[00:29:30 WRN] Starting host on version 2.0.62.0
[00:29:32 INF] TaskRunner started.
[00:29:32 DBG] Initializing TorrentRunner
[00:29:32 DBG] {"General":{"LogLevel":0,"DownloadLimit":5,"UnpackLimit":3,"Categories":"Films,S\u00E9rie,radarr","RunOnTorrentCompleteFileName":null,"RunOnTorrentCompleteArguments":null,"AuthenticationType":0,"CopyAddedTorrents":null},"DownloadClient":{"Client":0,"DownloadPath":"/data/downloads","MappedPath":"/data/downloads","MaxSpeed":0,"ParallelCount":100,"ChunkCount":8,"Timeout":5000,"ProxyServer":null,"Aria2cUrl":"http://127.0.0.1:6800/jsonrpc","Aria2cSecret":"*****","Aria2cDownloadPath":null,"RcloneMountPath":"/mnt/rd/"},"Provider":{"Provider":1,"ApiKey":"*****","AutoImport":false,"AutoDelete":false,"Timeout":10,"CheckInterval":10,"Default":{"HostDownloadAction":0,"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"IncludeRegex":null,"ExcludeRegex":null,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Integrations":{"Default":{"HostDownloadAction":0,"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"IncludeRegex":null,"ExcludeRegex":null,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Gui":{"Default":{"HostDownloadAction":0,"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"IncludeRegex":null,"ExcludeRegex":null,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Watch":{"Path":null,"ErrorPath":null,"ProcessedPath":null,"Interval":60,"Default":{"HostDownloadAction":0,"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"IncludeRegex":null,"ExcludeRegex":null,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}}
[00:29:32 DBG] Found 0 not completed torrents
[00:29:32 DBG] TorrentRunner Initialized
[00:29:32 INF] UpdateChecker started, currently on version v2.0.62.
[00:29:32 INF] WatchFolderChecker started.
[00:29:32 INF] ProviderUpdater started.
[00:29:39 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[00:29:39 DBG] Method: GET, Path: /api/v2/app/preferences
[00:29:39 DBG] Method: GET, Path: /api/v2/torrents/info
[00:29:50 DBG] Method: GET, Path: /Api/Torrents
[00:29:55 WRN] 304: /index.html
[00:29:55 WRN] 101: /hub
[00:29:55 DBG] Method: POST, Path: /api/v2/torrents/add, Form: paused: False
[00:29:55 WRN] 304: /polyfills.bc0070be939c8a90.js
[00:29:55 WRN] 304: /main.65c3145776ff3b61.js
[00:29:55 WRN] 304: /styles.e0d9d5dcd8df4190.css
[00:29:55 WRN] 304: /runtime.52f1d05aa6c3afea.js
[00:29:55 DBG] Add file
[00:29:56 DBG] bytes System.Byte[]
[00:29:56 DBG] Method: GET, Path: /Api/Torrents
[00:29:57 DBG] Adding 0254C4688CAEC1698F432C387FD80FC9F5CA7CB6 torrent file for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:57 DBG] Processing 1 torrents
[00:29:57 DBG] Currently 0 queued downloads and 0 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:57 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:57 DBG] Selecting files for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:57 DBG] Method: POST, Path: /api/v2/torrents/add, Form: paused: False
[00:29:57 DBG] Add file
[00:29:57 DBG] bytes System.Byte[]
[00:29:57 DBG] Adding D77E288A91600B52A190201BC2FA8D4B24B2442A torrent file for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:29:57 DBG] Updating torrent info from debrid provider
[00:29:58 DBG] Finished updating torrent info from debrid provider, next update in 10 seconds
[00:29:58 DBG] Processing 2 torrents
[00:29:58 DBG] Currently 0 queued downloads and 0 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:58 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:58 DBG] Creating downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:58 DBG] Getting download links for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:58 DBG] Selecting links:
[00:29:58 DBG] xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv (2410280978b) xxxxxxxxxxxxxxxxxxxxxxxxxxx, contains files:
/xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv
[00:29:58 DBG] xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo (6895b) xxxxxxxxxxxxxxxxxxxxxxxxxxx, contains files:
/xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo
[00:29:58 DBG]  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:58 DBG] Currently 0 queued downloads and 0 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:29:58 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:29:58 DBG] Selecting files for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:29:59 DBG] Method: POST, Path: /api/v2/torrents/add, Form: paused: False
[00:29:59 DBG] Add file
[00:29:59 DBG] bytes System.Byte[]
[00:29:59 DBG] Processing 2 torrents
[00:29:59 DBG] Currently 2 queued downloads and 0 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:59 DBG] Processing to download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (47c36cbc-eb51-460a-a287-ed1a84ecbb80) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:59 DBG] Unrestricting links for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (47c36cbc-eb51-460a-a287-ed1a84ecbb80) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:59 DBG] Unrestricting link for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (47c36cbc-eb51-460a-a287-ed1a84ecbb80) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:59 DBG] Adding 2FDD49A3E3402509B4C4309A48DC27202EF1539C torrent file for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:29:59 DBG] Setting download path to /data/downloads for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (47c36cbc-eb51-460a-a287-ed1a84ecbb80) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:59 DBG] Starting download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (47c36cbc-eb51-460a-a287-ed1a84ecbb80) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:29:59 DBG] Starting download of xxxxxxxxxxxxxxxxxxxxxxxxxxx, writing to path: /data/downloads/xxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv
[00:30:01 DBG] Received ID b75f9222-e6e0-4cd5-87dd-b6a0015db00e for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (47c36cbc-eb51-460a-a287-ed1a84ecbb80) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:01 DBG] Marking download as started for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (47c36cbc-eb51-460a-a287-ed1a84ecbb80) remoteID: b75f9222-e6e0-4cd5-87dd-b6a0015db00e for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:01 DBG] Processing to download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:01 DBG] Unrestricting links for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:01 DBG] Unrestricting link for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:01 DBG] Setting download path to /data/downloads for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:01 DBG] Starting download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:01 DBG] Starting download of https://c5d6e7.debrid.it/dl/30ogewma687/xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo, writing to path: /data/downloads/xxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo
[00:30:02 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[00:30:02 DBG] Method: GET, Path: /api/v2/app/preferences
[00:30:02 DBG] Method: GET, Path: /api/v2/torrents/info
[00:30:02 DBG] Received ID 4f025e4a-86bb-487d-b817-9932c60d111b for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:02 DBG] Marking download as started for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID: 4f025e4a-86bb-487d-b817-9932c60d111b for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:02 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:02 DBG] Waiting for downloads to complete. 0/2 complete (0%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:02 DBG] Currently 0 queued downloads and 2 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:02 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:02 DBG] Creating downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:02 DBG] Getting download links for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:02 DBG] Selecting links:
[00:30:02 DBG] xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv (2012083186b) xxxxxxxxxxxxxxxxxxxxxxxxxxx, contains files:
/xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv
[00:30:02 DBG] xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo (6895b) xxxxxxxxxxxxxxxxxxxxxxxxxxx, contains files:
/xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo
[00:30:02 DBG]  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:02 DBG] TorrentRunner Tick End (took 3072ms)
[00:30:03 DBG] TorrentRunner Tick Start, 2 active downloads, 0 active unpacks
[00:30:03 DBG] Processing 1 completed downloads
[00:30:03 DBG] Processing download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID: 4f025e4a-86bb-487d-b817-9932c60d111b for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Download finished successfully for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID: 4f025e4a-86bb-487d-b817-9932c60d111b for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Removed from ActiveDownloadClients for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID: 4f025e4a-86bb-487d-b817-9932c60d111b for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Processing 3 torrents
[00:30:03 DBG] Currently 0 queued downloads and 1 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Starting unpack for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID: 4f025e4a-86bb-487d-b817-9932c60d111b for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Found file name xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID: 4f025e4a-86bb-487d-b817-9932c60d111b for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] No need to unpack, setting it as unpacked for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (1fdc8f29-e1b0-4909-acb5-2f2ba2ca57a6) remoteID: 4f025e4a-86bb-487d-b817-9932c60d111b for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Waiting for downloads to complete. 1/2 complete (0%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:30:03 DBG] Currently 2 queued downloads and 1 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:03 DBG] Processing to download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (aa98f464-e36e-4d4e-af0b-6ae2b082ca07) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:03 DBG] Unrestricting links for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (aa98f464-e36e-4d4e-af0b-6ae2b082ca07) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:03 DBG] Unrestricting link for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (aa98f464-e36e-4d4e-af0b-6ae2b082ca07) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:04 DBG] Setting download path to /data/downloads for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (aa98f464-e36e-4d4e-af0b-6ae2b082ca07) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:04 DBG] Starting download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (aa98f464-e36e-4d4e-af0b-6ae2b082ca07) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:04 DBG] Starting download of xxxxxxxxxxxxxxxxxxxxxxxxxxx, writing to path: /data/downloads/xxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv
[00:30:05 DBG] Received ID 117d6765-1ae4-4251-95ce-270affea14da for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (aa98f464-e36e-4d4e-af0b-6ae2b082ca07) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:05 DBG] Marking download as started for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.mkv. Completed: 0%, avg speed: 0bytes/s (aa98f464-e36e-4d4e-af0b-6ae2b082ca07) remoteID: 117d6765-1ae4-4251-95ce-270affea14da for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:05 DBG] Processing to download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (dda9a49a-d597-454c-b923-9b712296813e) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:05 DBG] Unrestricting links for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (dda9a49a-d597-454c-b923-9b712296813e) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:05 DBG] Unrestricting link for download xxxxxxxxxxxxxxxxxxxxxxxxxxx. Completed: 0%, avg speed: 0bytes/s (dda9a49a-d597-454c-b923-9b712296813e) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:05 DBG] Setting download path to /data/downloads for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (dda9a49a-d597-454c-b923-9b712296813e) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:05 DBG] Starting download for download xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo. Completed: 0%, avg speed: 0bytes/s (dda9a49a-d597-454c-b923-9b712296813e) remoteID:  for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:30:06 DBG] Starting download of xxxxxxxxxxxxxxxxxxxxxxxxxxx, writing to path: /data/downloads/xxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxx.nfo
```

When stuck, looping :

```
[00:33:42 DBG] Processing 3 torrents
[00:33:42 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:42 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:42 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:42 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:42 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:42 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:42 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:42 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:42 DBG] Waiting for downloads to complete. 1/2 complete (7%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:43 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[00:33:43 DBG] Method: GET, Path: /api/v2/app/preferences
[00:33:43 DBG] Method: GET, Path: /api/v2/torrents/info
[00:33:43 DBG] TorrentRunner Tick Start, 3 active downloads, 0 active unpacks
[00:33:43 DBG] Processing 3 torrents
[00:33:43 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:43 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:43 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:43 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:43 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:43 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:43 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:43 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:43 DBG] Waiting for downloads to complete. 1/2 complete (7%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:44 DBG] TorrentRunner Tick Start, 3 active downloads, 0 active unpacks
[00:33:44 DBG] Processing 3 torrents
[00:33:44 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:44 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:44 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:44 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:44 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:44 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:44 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:44 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:44 DBG] Waiting for downloads to complete. 1/2 complete (7%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:46 DBG] TorrentRunner Tick Start, 3 active downloads, 0 active unpacks
[00:33:46 DBG] Processing 3 torrents
[00:33:46 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:46 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:46 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520834 - Ready 100%) (75a439e4-1c91-4416-8aa1-b1c2462a5f19)
[00:33:46 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:46 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:46 DBG] Waiting for downloads to complete. 1/2 complete (9%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520840 - Ready 100%) (871246f1-0573-477f-8923-2cca7543969a)
[00:33:46 DBG] Currently 0 queued downloads and 3 total active downloads for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:46 DBG] Processing for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)
[00:33:46 DBG] Waiting for downloads to complete. 1/2 complete (7%) for torrent xxxxxxxxxxxxxxxxxxxxxxxxxxx (222520849 - Ready 100%) (8d8f1be9-a000-4107-9968-a8d0402f3c36)

```

**Comment by rogerfar** [comment]
So it's downloading but it's just stuck at 7% and 9% correct?

It shouldn't matter if you have AllDebrid because it's already downloading at that point. 

But if you said you tried the Bezzad downloader and it's very slow, could there just be an issue with the connection to AllDebrids servers? 

What happens if you take one of those unrestricted links and download them just with the browser? And what about if you do a wget inside the container?

**Comment by Elrau** [comment]
Yes, this number change. From the test this morning it was 16%.

From my computer browser, everything goes perfectly, full speed, no drop.
From Docker host and container with wget, file download completely but huge drop at some points. Nothing else taking bandwidth on server.

Both server are on the same switch with 1Gb/s, only difference is computer on Windows 10 and server on Debian 12 VM on ESXi.

**Comment by rogerfar** [comment]
That's curious, if you would root into the ESXi host itself, is it still fast? And what about another docker container? 

It's hard to troubleshoot these kind of issues, but there's quite a few users who are having inconsistent speed issues, myself have no issues, running on a Proxmox Docker LXC, so it's pretty difficult to know where the problem is.

**Comment by Elrau** [comment]
Yes this kind of problem are hard to troubleshoot.
I will not be able for a few days to test it but I come back to you as soon as possible

**Comment by rogerfar** [comment]
If it stays at 0MB/s then it's possible that it's flushing to disk. I have it at 4 and it goes up and down too yeah. I thought there was a limit, but I can't find it anywhere anymore. I think they're pretty royal with the limits.

**Comment by rogerfar** [comment]
I did some testing and found that these settings work well:
https://github.com/rogerfar/rdt-client/issues/296#issuecomment-2043919951
