### ISSUE TITLE
Symlink Downloader is not creating symlinks

### ISSUE THREAD

**Issue by ashipaek0** [rogerfar/rdt-client#449]
**What version are you using?  

  *latest docker version*

**Wat OS are you running?   

  *Ubuntu 20.04*

**Are you using Docker or as a service?  

  *Docker*

**Which debrid provider are you using?  

   *Real-Debrid*

**Which downloader are you using?  

    *Symlink Downloader*

**Please attach a log file here with the log setting set to debug*

```
2024-04-03 13:50:04.566 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Starting download for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:04.566 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Starting symlink resolving of https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4, writing to path: /media/gdrive/symlinks/radarr/Suze (2023) [1080p] [WEBRip] [YTS.MX]/Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:04.566 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Searching /mnt/zurg/__all__ for Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:04.566 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Cancelling download https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4
2024-04-03 13:50:04.566 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: No ID received for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:04.566 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:04.566 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 0/1 complete (0%) for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.565 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2024-04-03 13:50:05.565 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 1 queued downloads and 0 total active downloads for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.565 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing to download for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.565 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Unrestricting links for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.566 +00:00 [DBG] RdtClient.Service.Services.Torrents: Unrestricting link for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.687 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Setting download path to /media/gdrive/symlinks/radarr for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.687 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Starting download for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.688 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Starting symlink resolving of https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4, writing to path: /media/gdrive/symlinks/radarr/Suze (2023) [1080p] [WEBRip] [YTS.MX]/Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:05.688 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Searching /mnt/zurg/__all__ for Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:05.688 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Cancelling download https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4
2024-04-03 13:50:05.688 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: No ID received for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.688 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:05.688 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 0/1 complete (0%) for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.067 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Updating torrent info from debrid provider
2024-04-03 13:50:06.688 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2024-04-03 13:50:06.689 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 1 queued downloads and 0 total active downloads for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.689 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing to download for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.689 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Unrestricting links for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.690 +00:00 [DBG] RdtClient.Service.Services.Torrents: Unrestricting link for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.816 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Finished updating torrent info from debrid provider, next update in 10 seconds
2024-04-03 13:50:06.919 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Setting download path to /media/gdrive/symlinks/radarr for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.919 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Starting download for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.920 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Starting symlink resolving of https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4, writing to path: /media/gdrive/symlinks/radarr/Suze (2023) [1080p] [WEBRip] [YTS.MX]/Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:06.920 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Searching /mnt/zurg/__all__ for Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:06.920 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Cancelling download https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4
2024-04-03 13:50:06.920 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: No ID received for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.920 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:06.920 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 0/1 complete (0%) for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:07.920 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2024-04-03 13:50:07.920 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 1 queued downloads and 0 total active downloads for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:07.920 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing to download for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:07.921 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Unrestricting links for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:07.921 +00:00 [DBG] RdtClient.Service.Services.Torrents: Unrestricting link for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:08.026 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Setting download path to /media/gdrive/symlinks/radarr for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:08.026 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Starting download for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:08.026 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Starting symlink resolving of https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4, writing to path: /media/gdrive/symlinks/radarr/Suze (2023) [1080p] [WEBRip] [YTS.MX]/Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:08.027 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Searching /mnt/zurg/__all__ for Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4
2024-04-03 13:50:08.027 +00:00 [DBG] RdtClient.Service.Services.Downloaders.SymlinkDownloader: Cancelling download https://23.download.real-debrid.com/d/CQBIGTEQJE6O6/Suze.2023.1080p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4
2024-04-03 13:50:08.027 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: No ID received for download Suze.2023.1080p.WEBRip.x264.AAC-[YTS.MX].mp4. Completed: 0%, avg speed: 0bytes/s (9a6eda9e-61d1-45e4-877e-9a4fef3af888) remoteID:  for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:08.027 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
2024-04-03 13:50:08.027 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Waiting for downloads to complete. 0/1 complete (0%) for torrent Suze (2023) [1080p] [WEBRip] [YTS.MX] (6WPPH55XPXVYA - downloaded 100%) (78db7776-b815-4fcd-bfe8-37b918232051)
```*

**Comment by ArrJayyy** [comment]
Yeah, i was having the same issue and opened a post as well, many others have opened similar ones too.  Although i don't know what i did to fix other then just tinkering with the settings. I'm running it on windows at the moment but i have also ran it on ubuntu in docker. I followed this guide for ubuntu https://puksthepirate.notion.site/eebe27d130fa400c8a0536cab9d46eb3?v=0cf094af30854b628e47ec17010725a5.

**Comment by ashipaek0** [comment]
> Yeah, i was having the same issue and opened a post as well, many others have opened similar ones too. Although i don't know what i did to fix other then just tinkering with the settings. I'm running it on windows at the moment but i have also ran it on ubuntu in docker. I followed this guide for ubuntu https://puksthepirate.notion.site/eebe27d130fa400c8a0536cab9d46eb3?v=0cf094af30854b628e47ec17010725a5.

I think the pukabyte rdtclient fork is the difference.

unfortunately that particular build only works with AMD64 and not ARM64 like i have

**Comment by rogerfar** [comment]
I will see if I can merge those changes in RDT here, not sure why there's such a separate build.

I did find an issue with the download client setting that would try to wrong downloader, so maybe that has something to do with it? I will push a fix for that in the next build.

**Comment by ArrJayyy** [comment]
> I will see if I can merge those changes in RDT here, not sure why there's such a separate build.
> 
> I did find an issue with the download client setting that would try to wrong downloader, so maybe that has something to do with it? I will push a fix for that in the next build.

Its working fairly well now on windows, but it does occasionally break. I think it seems to depend on which torrent it grabs, not sure why tho. Looking forward to the new build, thanks.

**Comment by rogerfar** [comment]
I pushed a new build now, check if it's more reliable. Also it's now hard failing when the process fails instead of endlessly retrying with no real feedback. Hopefully this will show errors quicker and make it easier to fix.

**Comment by ArrJayyy** [comment]
> I pushed a new build now, check if it's more reliable. Also it's now hard failing when the process fails instead of endlessly retrying with no real feedback. Hopefully this will show errors quicker and make it easier to fix.

Seems like its working well so far. I'll update again if I encounter an issue.

**Comment by ashipaek0** [comment]
confirm here too

its doing the symlinks, but stuck on queued for unpacking

also once one link gets into that mode the other links don't get processed until the one marked unpacking gets deleted

**Comment by rogerfar** [comment]
@ArrJayyy the logs indicate:

```
Searching Z:\torrents for Vengeance in the Making.mkv (attempt #10)...
 Could not find file from rclone mount! 
```
Does this file not exist in Z:\torrents?

**Comment by rogerfar** [comment]
I setup a raidrive myself and started testing, there were some oddities in the symlink downloader. Try the latest version and see if it works better.

**Comment by ArrJayyy** [comment]
> I setup a raidrive myself and started testing, there were some oddities in the symlink downloader. Try the latest version and see if it works better.

Ill try it out. As for ur other comment, the file did exist in the rclone mount i could also play it too but that torrent that got downloaded had additional files i didnt need and that was one of them, but that was due to it being over the 100MB limit so i increased that. I think i just chose i diff torrent after that manually. I wonder now tho maybe it has issues when a torrent contains multiple files cuz that was just one example.

**Comment by eoghan2t9** [comment]
Can also confirm the same issue on my install of .66. downloads are 100% on RD and extracted etc. but RDTC doesn't seem to want to symlink the files. I'll gather some log snippets for you

**Comment by rogerfar** [comment]
Could you please post full logs, the snippets aren't giving enough information to see the actual errors.

**Comment by rogerfar** [comment]
So the error is: `Could not find file from rclone mount! for download 12 Years a Slave 2013 1080p Blu-ray Remux AVC DTS-HD MA 5.1 - KRaLiMaRKo.mkv.`

Could you show the full path of where this file is located on your webdav? And also what your rmount path in the settings?

I found that RD does some odd things with the folders when it puts them in webdav.

**Comment by karan** [comment]
I'm on phone now so can't but I verified that the path is correct (and consistent with https://github.com/rogerfar/rdt-client/issues/449#issuecomment-2044167170).

The mount path is `/data/debrid-rd/torrents`.

Again going back to .65 fixed it all for me (with no other changes made).

**Comment by eoghan2t9** [comment]
My mount paths are exactly the same as in this guide. I have also reverted back to 65 and all working again although getting an awful lot of stalled downloads for some reason. So I'll have to test that part.

I'll also get you a full log although my log seems to be quite large in terms of size so might be worth adding some form of log rotation so they are a more manageable size for uploading etc.


https://puksthepirate.notion.site/Guide-Zurg-RDT-Prowlarr-Arrs-Petio-Autoscan-Plex-Scannarr-eebe27d130fa400c8a0536cab9d46eb3

**Comment by rogerfar** [comment]
I added another fix that fixes the issue from @d3mystified.

But please, if a torrent is stuck I cannot do anything without full logs, at least the magnet to the torrent as a pastebin.

**Comment by maulik9898** [comment]
I am also facing same issue. Last working rdt version is 6.0.65 for me. below is logs for version 6.0.68 and 6.0.65
[6.0.68 logs](https://pastebin.com/YXFvU2jt)
[6.0.65 logs](https://pastebin.com/sg1NJs6b)

`magnet:?xt=urn:btih:9c40df27f04f80a017f024d9897130cf696a1e40`

**Comment by eoghan2t9** [comment]
@rogerfar with the .69 version the rclone path still isnt working as it still throwing this error

`Could not find file from rclone mount!`

Here is the full log with a magnet link for one of the offending downloads the rclone mount is 100% mounted and working as plex  etc is still working
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/14932052/rdtclient.log)

[https://pastebin.com/Ry0dQid3](https://pastebin.com/Ry0dQid3)

**Comment by rogerfar** [comment]
@maulik9898 I tried both your magnets on 69 and they worked for me.

@eoghan2t9 also that magnet worked for me, so not sure what's different. 

I will add some logging in .70 to see what it's trying to search for and what is available.

**Comment by eoghan2t9** [comment]
@rogerfar perfect mate thanks I have double checked the rclone path and it's valid I even chmod 777 the folder in case it was a random permissions issue and still no joy.

**Comment by rogerfar** [comment]
If you can update to. 70 and post logs then I can see what it's trying to do.

**Comment by funkypenguin** [comment]
Hey @rogerfar! Thanks for this - I can reproduce the above problem in .70 - I'm using zurg `v0.9.3-hotfix.11` for the rclone mount.

```
[01:52:32 DBG] Adding 456183821E280262BA8E71F8598967EEADDD971A magnet link magnet:?xt=urn:btih:456183821E280262BA8E71F8598967EEADDD971A&dn=White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG&tr=http%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.auctor.tv%3a6969%2fannounce&tr=udp%3a%2f%2fopentracker.i2p.rocks%3a6969%2fannounce&tr=https%3a%2f%2fopentracker.i2p.rocks%3a443%2fannounce&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a6969%2fannounce&tr=http%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2fopen.stealth.si%3a80%2fannounce&tr=udp%3a%2f%2ftracker.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2ftracker.moeking.me%3a6969%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2fuploads.gamecoast.net%3a6969%2fannounce&tr=udp%3a%2f%2ftracker1.bt.moack.co.kr%3a80%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.theoks.net%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.skyts.net%3a6969%2fannounce&tr=udp%3a%2f%2ftracker-udp.gbitt.info%3a80%2fannounce&tr=udp%3a%2f%2fopen.tracker.ink%3a6969%2fannounce&tr=udp%3a%2f%2fmovies.zsw.ca%3a6969%2fannounce for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
```

```

[01:52:42 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Selecting files for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Seleting files for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Determining which files are already available on RealDebrid for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Found 3/3 available files on RealDebrid for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Selecting 1/3 files for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Determining which files are over 5242880 bytes for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Found 1 files that match the minimum file size criterea for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:42 DBG] Selecting files:
[01:52:42 DBG] 3: /White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (1375091338b)
[01:52:42 DBG]  for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:44 DBG] Processing 1 torrents
[01:52:44 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:44 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:44 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[01:52:44 DBG] Method: GET, Path: /api/v2/app/preferences
[01:52:44 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=sonarr
[01:52:45 DBG] Processing 1 torrents
[01:52:45 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:45 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:45 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[01:52:45 DBG] Method: GET, Path: /api/v2/app/preferences
[01:52:45 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=sonarr4k
[01:52:46 DBG] Processing 1 torrents
[01:52:46 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:46 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:47 DBG] Processing 1 torrents
[01:52:47 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:47 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:48 DBG] Processing 1 torrents
[01:52:48 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:48 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:49 DBG] Processing 1 torrents
[01:52:49 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:49 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:49 DBG] Updating torrent info from debrid provider
[01:52:50 DBG] Processing 1 torrents
[01:52:50 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:50 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - waiting_files_selection 0%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:50 DBG] Finished updating torrent info from debrid provider, next update in 10 seconds
[01:52:51 DBG] Processing 1 torrents
[01:52:51 DBG] Currently 0 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:51 DBG] Processing for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:51 DBG] Creating downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:51 DBG] Found 1 links for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:51 DBG] https://real-debrid.com/d/FIRNA6QWBRDEMQ4JPQ74E7VPIM for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:51 DBG] Torrent has 1 selected files out of 3 files, found 1 links, torrent ended: 01/07/2024 18:52:50 +02:00 for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:51 DBG] Matched 1 selected files expected files to 1 found files for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Processing 1 torrents
[01:52:52 DBG] Currently 1 queued downloads and 0 total active downloads for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Processing to download for download https://real-debrid.com/d/FIRNA6QWBRDEMQ4JPQ74E7VPIM. Completed: 0%, avg speed: 0bytes/s (a204c859-b049-4e94-bf74-fb4d0b36338e) remoteID:  for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Unrestricting links for download https://real-debrid.com/d/FIRNA6QWBRDEMQ4JPQ74E7VPIM. Completed: 0%, avg speed: 0bytes/s (a204c859-b049-4e94-bf74-fb4d0b36338e) remoteID:  for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Unrestricting link for download https://real-debrid.com/d/FIRNA6QWBRDEMQ4JPQ74E7VPIM. Completed: 0%, avg speed: 0bytes/s (a204c859-b049-4e94-bf74-fb4d0b36338e) remoteID:  for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Marking download as started for download White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4. Completed: 0%, avg speed: 0bytes/s (a204c859-b049-4e94-bf74-fb4d0b36338e) remoteID:  for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Setting download path to /storage/symlinks/downloads/radarr for download White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4. Completed: 0%, avg speed: 0bytes/s (a204c859-b049-4e94-bf74-fb4d0b36338e) remoteID:  for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Starting download for download White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4. Completed: 0%, avg speed: 0bytes/s (a204c859-b049-4e94-bf74-fb4d0b36338e) remoteID:  for torrent White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG (JIMGWICQWK7DK - downloaded 100%) (0becb743-0e55-4f73-8df0-41167a655977)
[01:52:52 DBG] Starting symlink resolving of https://34.download.real-debrid.com/d/ODZPBXJ67R4MM/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4, writing to path: White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4
[01:52:52 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #0)...
[01:52:52 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:52 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:52 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #1)...
[01:52:52 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:52 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:53 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #2)...
[01:52:53 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:53 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:55 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #3)...
[01:52:55 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:55 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:58 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #4)...
[01:52:58 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:52:58 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:53:00 DBG] Updating torrent info from debrid provider
[01:53:00 DBG] Finished updating torrent info from debrid provider, next update in 10 seconds
[01:53:02 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #5)...
[01:53:02 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:53:02 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:53:07 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #6)...
[01:53:07 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:53:07 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:53:10 DBG] Updating torrent info from debrid provider
[01:53:11 DBG] Finished updating torrent info from debrid provider, next update in 10 seconds
[01:53:13 DBG] Searching /storage/realdebrid-zurg/__all__ for White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4 (attempt #7)...
[01:53:13 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
[01:53:13 DBG] Searching /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4...
^C
```

and yet, on the filesystem:

```
elfhosted:/app# ls -la /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG\/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4
-rw-r--r--    1 elfie    elfie    1375091338 Jan  7 17:52 /storage/realdebrid-zurg/__all__/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG/White.Zombie.1932.1080p.BluRay.H264.AAC-RARBG.mp4
elfhosted:/app#
```

**Comment by maulik9898** [comment]
@rogerfar which machine are you using ( Windows or linux ). I think this isuue only happens with linux machine.

**Comment by rogerfar** [comment]
Yeah I'm using windows, I see some `\/` in the paths, that must be a problem. I'll push a fix for that now.

If it still happens, if you could wait till attempt #9 and get the actual error to pop up in the logs, it outputs a log of the mount path directory structure, then I can compare what it's looking for and what there is.

**Comment by maulik9898** [comment]
outof curiosity why don't we use Directory.GetFiles method to find file. This is what codebase uses in 6.0.63 and its working flowless. https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=net-8.0

**Comment by rogerfar** [comment]
I thought of that, but I did find that traversing the WebDAV drive with a large amount of files is slow, because you're not connecting to a local drive but remotely.

And there is the possibility that the same file exists in multiple places, it's small, but it's possible.

For now I want to see if this works, because I checked various magnets and they all kind of show the same behaviour on how they are placed on the WebDAV drives.

**Comment by maulik9898** [comment]
got it

**Comment by maulik9898** [comment]
we can close this issue. 2.0.71 works

**Comment by eoghan2t9** [comment]
@rogerfar can confirm the issue has been fixed thanks your a genius 🎉🎉🎉

**Comment by eoghan2t9** [comment]
@rogerfar might have spoken too soon lol I'll grab the log when I'm home

![Screenshot_20240411-063243.png](https://github.com/rogerfar/rdt-client/assets/911750/9ec9a254-fcdb-494c-8b17-cf6d1ff2104e)

**Comment by eoghan2t9** [comment]
Just thinking out loud say I have a download and in the file name there is something like this

[eztv.li]

Could this part of your code be processing that and freaking out thinking it's part of your trim array?

TrimEnd(['\\', '/'])

**Comment by emanuelbaltaretu** [comment]
> > Yeah, i was having the same issue and opened a post as well, many others have opened similar ones too. Although i don't know what i did to fix other then just tinkering with the settings. I'm running it on windows at the moment but i have also ran it on ubuntu in docker. I followed this guide for ubuntu https://puksthepirate.notion.site/eebe27d130fa400c8a0536cab9d46eb3?v=0cf094af30854b628e47ec17010725a5.
> 
> I think the pukabyte rdtclient fork is the difference.
> 
> unfortunately that particular build only works with AMD64 and not ARM64 like i have

Yeah, I was using the pukabyte fork as well, I just got the latest version from @rogerfar, I will come back to report, so far no issues from a few tests.

**Comment by ashipaek0** [comment]
> > > Yeah, i was having the same issue and opened a post as well, many others have opened similar ones too. Although i don't know what i did to fix other then just tinkering with the settings. I'm running it on windows at the moment but i have also ran it on ubuntu in docker. I followed this guide for ubuntu https://puksthepirate.notion.site/eebe27d130fa400c8a0536cab9d46eb3?v=0cf094af30854b628e47ec17010725a5.
> > 
> > 
> > I think the pukabyte rdtclient fork is the difference.
> > unfortunately that particular build only works with AMD64 and not ARM64 like i have
> 
> Yeah, I was using the pukabyte fork as well, I just got the latest version from @rogerfar, I will come back to report, so far no issues from a few tests.

Does it successfully unpack the downloads now?

**Comment by ashipaek0** [comment]
> > > Yeah, i was having the same issue and opened a post as well, many others have opened similar ones too. Although i don't know what i did to fix other then just tinkering with the settings. I'm running it on windows at the moment but i have also ran it on ubuntu in docker. I followed this guide for ubuntu https://puksthepirate.notion.site/eebe27d130fa400c8a0536cab9d46eb3?v=0cf094af30854b628e47ec17010725a5.
> > 
> > 
> > I think the pukabyte rdtclient fork is the difference.
> > unfortunately that particular build only works with AMD64 and not ARM64 like i have
> 
> Yeah, I was using the pukabyte fork as well, I just got the latest version from @rogerfar, I will come back to report, so far no issues from a few tests.

Does it successfully unpack the downloads now?

**Comment by rogerfar** [comment]
@eoghan2t9 have you been able to get the logs?

@ashipaek0 Maybe wrong issue? This shouldn't affect unpacking as it's all symlinked.

**Comment by emanuelbaltaretu** [comment]
So I was able to do a few more tests but not that many unfortunately as I have run in other unrelated issue and I will be away for a while. Besides the fact that it still takes radarr a while to figure out it finished "downloading" all good so far, maybe the others that had the same issue can report further.

Many thanks @rogerfar for what you are doing!

**Comment by eoghan2t9** [comment]
@rogerfar yes mate I have a few logs for you I let them fail over and over again just to get you as much info as possible

[rdtclient_001.log](https://github.com/rogerfar/rdt-client/files/14953810/rdtclient_001.log)
[rdtclient_002.log](https://github.com/rogerfar/rdt-client/files/14953811/rdtclient_002.log)
[rdtclient_224.log](https://github.com/rogerfar/rdt-client/files/14953812/rdtclient_224.log)
[rdtclient_225.log](https://github.com/rogerfar/rdt-client/files/14953813/rdtclient_225.log)
[rdtclient_226.log](https://github.com/rogerfar/rdt-client/files/14953814/rdtclient_226.log)
[rdtclient_227.log](https://github.com/rogerfar/rdt-client/files/14953815/rdtclient_227.log)
[rdtclient_228.log](https://github.com/rogerfar/rdt-client/files/14953816/rdtclient_228.log)

**Comment by rogerfar** [comment]
Thanks @eoghan2t9, strangely I downloaded the exact same torrent and Real-Debrid put it on a different path in my webdav drive than it's showing on yours. I have added another path search in .73, that should resolve that.

**Comment by eoghan2t9** [comment]
@rogerfar Thanks mate ive updated so lets see how this one goes

**Comment by eoghan2t9** [comment]
@rogerfar Still getting the odd rclone mount errors heres the latest logs
[rdtclient_243.log](https://github.com/rogerfar/rdt-client/files/14954666/rdtclient_243.log)
[rdtclient_244.log](https://github.com/rogerfar/rdt-client/files/14954667/rdtclient_244.log)
[rdtclient_245.log](https://github.com/rogerfar/rdt-client/files/14954668/rdtclient_245.log)
[rdtclient_246.log](https://github.com/rogerfar/rdt-client/files/14954669/rdtclient_246.log)
[rdtclient_247.log](https://github.com/rogerfar/rdt-client/files/14954670/rdtclient_247.log)

**Comment by rogerfar** [comment]
Is it `/Fast.Furious.Spy.Racers.S01.1080p.WEB.x264-STRiFE[rartv]` ?

Can  you show a `ls` of where the file currently is sitting?

**Comment by eoghan2t9** [comment]
@rogerfar oddly that folder is no longer there so not sure if sonarr removed it or real debrid

**Comment by Toasterme** [comment]
v2.0.73, i'm having the "Could not find file from rclone mount!"

**Comment by PrevotYann** [comment]
Same for me v.2.0.73, torrents seems stuck to "waiting_files_selection" or "magnet_conversion" until i got to real debrid site with the popup file selection on Torrents page and do the selection

**Comment by rogerfar** [comment]
Guys I really need logs, those messages are impossible to troubleshoot without them.

@eoghan2t9 I checked the logs and if I do a search for that title through all files I can't find any occurrences of RDT deleting it. 

As a test could you re-add it to RDT or directly to read-debrid and see if it shows up?

**Comment by PrevotYann** [comment]
> Guys I really need logs, those messages are impossible to troubleshoot without them.
> 
> @eoghan2t9 I checked the logs and if I do a search for that title through all files I can't find any occurrences of RDT deleting it.
> 
> As a test could you re-add it to RDT or directly to read-debrid and see if it shows up?

The fact is that they don't even log in rdt logs :
[log.txt](https://github.com/rogerfar/rdt-client/files/14971288/log.txt)

My files still waiting on rd:
`{
		"id": "SSY2BUYOA3AUC",
		"filename": "Mushoku Tensei Jobless Reincarnation S02E14 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR).mkv",
		"hash": "a024d06836d02637e46b27b536424bdefa49133e",
		"bytes": 1445110736,
		"host": "real-debrid.com",
		"split": 2000,
		"progress": 0,
		"status": "magnet_conversion",
		"added": "2024-04-14T17:38:48.000Z",
		"links": [
			
		],
		"seeders": 0
	},
	{
		"id": "TO4BZYYTQFAWM",
		"filename": "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World S01E02 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR).mkv",
		"hash": "4c29e970b26417071cd0f7e92d70d0bc6de5f2cf",
		"bytes": 1442298769,
		"host": "real-debrid.com",
		"split": 2000,
		"progress": 0,
		"status": "waiting_files_selection",
		"added": "2024-04-14T17:22:48.000Z",
		"links": [
			
		]
	},
	{
		"id": "K5HG6HLD7ZOF6",
		"filename": "Grandpa and Grandma Turn Young Again S01E02 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR).mkv",
		"hash": "4d7ffa0d02ddde7269e4f9c2e37d33a7e03780cd",
		"bytes": 1442406636,
		"host": "real-debrid.com",
		"split": 2000,
		"progress": 0,
		"status": "magnet_conversion",
		"added": "2024-04-14T17:06:26.000Z",
		"links": [
			
		],
		"seeders": 0
	},
	{
		"id": "FCZSFMYZ5DDHG",
		"filename": "[Arcedo & Asayao] BLUE ARCHIVE The Animation - 01 VOSTFR (Web-Rip H.264 1080p E-AC-3).mkv",
		"hash": "f88fce34ea05f8eff746dfe5b40f44186493a032",
		"bytes": 759092218,
		"host": "real-debrid.com",
		"split": 2000,
		"progress": 0,
		"status": "magnet_conversion",
		"added": "2024-04-14T16:50:05.000Z",
		"links": [
			
		],
		"seeders": 0
	},
	{
		"id": "MAK2POHPK6J24",
		"filename": "Vampire Dormitory S01E02 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR).mkv",
		"hash": "499d4c6c56c3a324c066f849618d8a3fa02f91a8",
		"bytes": 1446245562,
		"host": "real-debrid.com",
		"split": 2000,
		"progress": 0,
		"status": "magnet_conversion",
		"added": "2024-04-14T16:49:18.000Z",
		"links": [
			
		],
		"seeders": 0
	},
	{
		"id": "DQW7DGAQMH6NK",
		"filename": "The Duke of Death and His Maid S03E02 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR).mkv",
		"hash": "4b234bb7c47a287af5abb6dec217b0c8cd336920",
		"bytes": 1437156814,
		"host": "real-debrid.com",
		"split": 2000,
		"progress": 0,
		"status": "waiting_files_selection",
		"added": "2024-04-14T16:17:26.000Z",
		"links": [
			
		]
	},`

**Comment by rogerfar** [comment]
@PrevotYann can you post logs in debug mode.

**Comment by PrevotYann** [comment]
> @PrevotYann can you post logs in debug mode.

Sure :

[rdtclient_006.log](https://github.com/rogerfar/rdt-client/files/14971431/rdtclient_006.log)
[rdtclient_007.log](https://github.com/rogerfar/rdt-client/files/14971432/rdtclient_007.log)
[rdtclient_008.log](https://github.com/rogerfar/rdt-client/files/14971433/rdtclient_008.log)

Oh, this is maybe because of rclone_rd that puts torrents in /shows or /movies or /default ?

So it doesn't find the file at the root of the rclone mount ?

**Comment by rogerfar** [comment]
RDTclient searches the path that you give in the settings under `rclone mount`. If it doesn't exist there, it will fail yeah.

**Comment by PrevotYann** [comment]
I'd be great to put more than one maybe ? As rclone_rd creates 3 sub folders

**Comment by rogerfar** [comment]
@PrevotYann can you show an example path of where the file is and what your mount path setting is?

**Comment by PrevotYann** [comment]
It looks like :
MontedRclonePath/shows
MontedRclonePath/movies
MontedRclonePath/default

This is how it is mapped with rclone_rd !

Note that I fixed my issue by mounting with classic rclone as webdav, then pointing my rclone Path to the webdavmount/torrents

**Comment by rogerfar** [comment]
I see, I'm not too familiar with how rclone_rd works, but how does it decide where to put a file?

**Comment by PrevotYann** [comment]
It use a go script with regexp to détermine if this is a show or movie, if
it doesn't find for each other it will put it in default.

(So for example : mount/movies/pathtomovie/movie.mkv)

**Comment by Raik0** [comment]
I seem to be having permission issues with the internal /app folder. Whenever a symlink is created to my downloads folder, instead of linking to the file, it creates a folder with the same name as the file. This is causing problems for Plex and the arrs, as they are unable to detect the file. Any assistance with this issue would be greatly appreciated.

**Comment by rogerfar** [comment]
@ashipaek0 you reported this issue yourself 2 weeks ago, are you saying it's still not working? Please post new logs with the latest version.

@PrevotYann I can add an option to specify the mount path like this: `/mtn/rdt/*` where * would be a wildcard directory it could traverse.

**Comment by ashipaek0** [comment]
> @ashipaek0 you reported this issue yourself 2 weeks ago, are you saying it's still not working? Please post new logs with the latest version.
> 
The symlinks now work.   

I just had a strange  situation where all the symlinks in TV folder stopped working, but the Movies folder kept working fine.

I just deleted the symlinks folder as it didn't seem to be worth while chasing how to repair over 10k symlinks

didn't see anything in the logs when i checked.

**Comment by rogerfar** [comment]
@PrevotYann I pushed an update that allows searching for subfolders.

If you change the setting of your mount path from `MontedRclonePath` to `MontedRclonePath/*`, it should iterate over the first subdirectory in `MontedRclonePath`.
