### ISSUE TITLE
Sonarr error: Unable to communicate with qBittorrent. Failed to connect to qBittorrent, check your settings.

### ISSUE THREAD

**Issue by mitch030504** [rogerfar/rdt-client#479]
**What version are you using?**
2.0.75
**Wat OS are you running?**
unraid
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
alldebrid
**Which downloader are you using?**
internal

sonarr is dropping an error in logs:
2024-04-27 08:23:02,698 DEBG 'sonarr' stdout output:
[Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [GET] http://192.168.88.2:6500/api/v2/torrents/info?category=tv: 500.InternalServerError (53 bytes)
Value was either too large or too small for an Int64.

**Comment by mitch030504** [comment]
it doesn't do this the whole time. it'll work for a bit and then randomly stop working and after a bit itll wwork again

**Comment by mitch030504** [comment]
getting this with debug on
[11:52:22 ERR] An unhandled exception has occurred while executing the request.
System.OverflowException: Value was either too large or too small for an Int64.
   at System.Decimal.ToInt64(Decimal d)
   at RdtClient.Service.Services.QBittorrent.TorrentInfo() in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 214
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsInfo(QBTorrentsInfoRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 136
   at lambda_method716(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 15
   at Program.<>c.<<<Main>$>b__0_13>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 157
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 15
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

**Comment by randadinata** [comment]
More info, if I remove entry with out-of-range value on the status field, the error message will disappear instantly. e.g.

`Torrent downloading (-9223372036854776000% - 0 B/s)`

**Comment by rogerfar** [comment]
This should be fixed in 2.0.76 now.

**Comment by billouetaudrey** [comment]
Hello

Seem not fixed on 2.0.78

"Value was either too large or too small for an Int64. "

I think it's when I have too much torrents

**Comment by rogerfar** [comment]
Can you show a log with a stack trace to the error?

**Comment by billouetaudrey** [comment]
I will as soon as I have this bug again ;) Sorry

**Comment by billouetaudrey** [comment]
> Can you show a log with a stack trace to the error?

`[v2.0.0.548] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings.
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.48:6500/api/v2/torrents/info?category=tv-whisparr]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 390
Value was either too large or too small for an Int64.
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 390
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.GetTorrents(QBittorrentSettings settings) in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 107
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 218
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in ./Whisparr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 90

[Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [GET] http://192.168.1.48:6500/api/v2/torrents/info?category=tv-whisparr: 500.InternalServerError (53 bytes)
Value was either too large or too small for an Int64. 
[Info] RssSyncService: Starting RSS Sync 
[Warn] Torznab: Indexer Pornotorrent rss sync didn't cover the period between 6/3/2024 1:28:34PM and 6/3/2024 1:59:35PM UTC. Search may be required. 
[Warn] Torznab: Indexer 0magnet rss sync didn't cover the period between 6/3/2024 1:28:35PM and 6/3/2024 1:59:35PM UTC. Search may be required. 
[Warn] Torznab: Indexer RarBG rss sync didn't cover the period between 3/17/2024 3:50:33PM and 3/21/2024 1:32:04PM UTC. Search may be required. 
[Info] DownloadDecisionMaker: Processing 697 releases 
[Info] RssSyncService: RSS Sync Completed. Reports found: 697, Reports grabbed: 0 
[Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [GET] http://192.168.1.48:6500/api/v2/torrents/info?category=tv-whisparr: 500.InternalServerError (53 bytes)
Value was either too large or too small for an Int64. 
[Warn] DownloadMonitoringService: Unable to retrieve queue and history items from RDT 

[v2.0.0.548] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings.
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.48:6500/api/v2/torrents/info?category=tv-whisparr]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 390
Value was either too large or too small for an Int64.
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 390
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.GetTorrents(QBittorrentSettings settings) in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 107
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in ./Whisparr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 218
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in ./Whisparr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 90

[Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [GET] http://192.168.1.48:6500/api/v2/torrents/info?category=tv-whisparr: 500.InternalServerError (53 bytes)
Value was either too large or too small for an Int64. `

`[14:01:47 ERR] An unhandled exception has occurred while executing the request.
System.OverflowException: Value was either too large or too small for an Int64.
   at System.Decimal.ToInt64(Decimal d)
   at RdtClient.Service.Services.QBittorrent.TorrentInfo() in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 216
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsInfo(QBTorrentsInfoRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 136
   at lambda_method140(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 15
   at Program.<>c.<<<Main>$>b__0_13>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 157
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 15
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
[14:01:47 ERR] An unhandled exception has occurred while executing the request.
System.OverflowException: Value was either too large or too small for an Int64.
   at System.Decimal.ToInt64(Decimal d)
   at RdtClient.Service.Services.QBittorrent.TorrentInfo() in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 216
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsInfo(QBTorrentsInfoRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 136
   at lambda_method140(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 15
   at Program.<>c.<<<Main>$>b__0_13>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 157
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 15
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
`

**Comment by rogerfar** [comment]
Thanks, I pushed a fix in 79. It can still error out, but it won't report the error to the client, but only log it. Not sure what number would trigger that, but at least it won't break.

**Comment by billouetaudrey** [comment]
Saw, will tell you if error happens again, thanks 😘
