### ISSUE TITLE
Feature request: Change base URL

### ISSUE THREAD

**Issue by popophobia** [rogerfar/rdt-client#49]
Can you add an option to change the base URL so the app can work with reverse proxy?

**Comment by rogerfar** [comment]
What reverse proxy are you using? I'm using it behind an IIS reverse proxy fine.

**Comment by timcoop3r** [comment]
I think is similar to the issue I was having before. I have it working with NGINX reverse proxy but only when the proxy url is the format 'example.com' or 'rdt-client.example.com' etc. (I use the latter to get around this)

'example.com/rdt-client' doesn't work out of the box, at least with Nginx like with some other apps presumably with some nuance with the way the URL gets passed through so it doesn't load.
Sonarr/Radarr has a 'base url' setting where you can tell the app it is at /sonaar through the proxy which allows them to work, otherwise they also have the same issue.

For reference I am suing 'nginx:alpine' container with the following config:

```
server {
    server_name rdt-client.example.com;

    location / {
       proxy_pass               http://x.x.x.x:6500/;
       proxy_redirect           off;
       proxy_set_header         Host                    $host;
       proxy_set_header         Upgrade                 $http_upgrade;
       proxy_set_header         Connection              $http_connection;
       proxy_set_header         X-Real-IP               $remote_addr;
       proxy_set_header         X-Forwarded-For         $proxy_add_x_forwarded_for;
    }
```

This config however does not work (but does with sonarr/radarr etc with base-url setting configured:

```
  server {
    server_name example.com;

    location /rdt-client/ {
       proxy_pass               http://x.x.x.x:6500;
       proxy_http_version       1.1;
       proxy_set_header         Host                    $host;
       proxy_set_header         Upgrade                 $http_upgrade;
       proxy_set_header         Connection              $http_connection;
       proxy_set_header         X-Real-IP               $remote_addr;
       proxy_set_header         X-Forwarded-For         $proxy_add_x_forwarded_for;
    }

**Comment by popophobia** [comment]
> 
> 
> I think is similar to the issue I was having before. I have it working with NGINX reverse proxy but only when the proxy url is the format 'example.com' or 'rdt-client.example.com' etc. (I use the latter to get around this)
> 
> 'example.com/rdt-client' doesn't work out of the box, at least with Nginx like with some other apps presumably with some nuance with the way the URL gets passed through so it doesn't load.
> Sonarr/Radarr has a 'base url' setting where you can tell the app it is at /sonaar through the proxy which allows them to work, otherwise they also have the same issue.
> 
> For reference I am using 'nginx:alpine' container with the following config:
> 
> ```
> server {
>     server_name rdt-client.example.com;
> 
>     location / {
>        proxy_pass               http://x.x.x.x:6500/;
>        proxy_redirect           off;
>        proxy_set_header         Host                    $host;
>        proxy_set_header         Upgrade                 $http_upgrade;
>        proxy_set_header         Connection              $http_connection;
>        proxy_set_header         X-Real-IP               $remote_addr;
>        proxy_set_header         X-Forwarded-For         $proxy_add_x_forwarded_for;
>     }
> ```
> 
> This config however does not work (but does with sonarr/radarr etc with base-url setting configured:
> 
> ```
>   server {
>     server_name example.com;
> 
>     location /rdt-client/ {
>        proxy_pass               http://x.x.x.x:6500;
>        proxy_http_version       1.1;
>        proxy_set_header         Host                    $host;
>        proxy_set_header         Upgrade                 $http_upgrade;
>        proxy_set_header         Connection              $http_connection;
>        proxy_set_header         X-Real-IP               $remote_addr;
>        proxy_set_header         X-Forwarded-For         $proxy_add_x_forwarded_for;
>     }
> ```

Yeap this is exactly the problem that I encounter. I can use NGINX to reverse proxy if I use a full domain name, but it won't work with a location /rdt-client/ URL.

**Comment by rogerfar** [comment]
That makes sense yes, let me do some digging to see how Angular does that.

**Comment by wlau2929** [comment]
> > I think is similar to the issue I was having before. I have it working with NGINX reverse proxy but only when the proxy url is the format 'example.com' or 'rdt-client.example.com' etc. (I use the latter to get around this)
> > 'example.com/rdt-client' doesn't work out of the box, at least with Nginx like with some other apps presumably with some nuance with the way the URL gets passed through so it doesn't load.
> > Sonarr/Radarr has a 'base url' setting where you can tell the app it is at /sonaar through the proxy which allows them to work, otherwise they also have the same issue.
> > For reference I am using 'nginx:alpine' container with the following config:
> > ```
> > server {
> >     server_name rdt-client.example.com;
> > 
> >     location / {
> >        proxy_pass               http://x.x.x.x:6500/;
> >        proxy_redirect           off;
> >        proxy_set_header         Host                    $host;
> >        proxy_set_header         Upgrade                 $http_upgrade;
> >        proxy_set_header         Connection              $http_connection;
> >        proxy_set_header         X-Real-IP               $remote_addr;
> >        proxy_set_header         X-Forwarded-For         $proxy_add_x_forwarded_for;
> >     }
> > ```
> > 
> > 
> > This config however does not work (but does with sonarr/radarr etc with base-url setting configured:
> > ```
> >   server {
> >     server_name example.com;
> > 
> >     location /rdt-client/ {
> >        proxy_pass               http://x.x.x.x:6500;
> >        proxy_http_version       1.1;
> >        proxy_set_header         Host                    $host;
> >        proxy_set_header         Upgrade                 $http_upgrade;
> >        proxy_set_header         Connection              $http_connection;
> >        proxy_set_header         X-Real-IP               $remote_addr;
> >        proxy_set_header         X-Forwarded-For         $proxy_add_x_forwarded_for;
> >     }
> > ```
> 
> Yeap this is exactly the problem that I encounter. I can use NGINX to reverse proxy if I use a full domain name, but it won't work with a location /rdt-client/ URL.

Did you get this to work with NGINX?

**Comment by timcoop3r** [comment]
I believe this is still being worked on

**Comment by rogerfar** [comment]
This should work now in 1.7.6. If you open the chrome dev console you will see a message like this:
```
setting base href to /
```
This is auto determine based on the path.

**Comment by edobez** [comment]
Given the NGINX configuration posted above, it still doesn't work for 1.7.8.
I tried different combinations of reverse proxy configuration but none of them work.
Has anybody found a configuration that works properly?

**Comment by ianb445** [comment]
Hi, 

No luck with nginx and various combinations of configs, being able to set the base URL in the configuration seems to key to resolving this.
