### ISSUE TITLE
Symlink doesn't work anymore after Radarr and Sonarr update

### ISSUE THREAD

**Issue by PandaOAA** [rogerfar/rdt-client#639]
**What version are you using?** Latest v2.0.91

**Wat OS are you running?** Windows

**Are you using Docker or as a service?** Service

**Which debrid provider are you using?** AllDebrid

**Which downloader are you using?** Symlink

**Please attach a log file here with the log setting set to debug**

Since Sonarr 4.0.11.2680 and Radarr 5.15.1.9463, the import of movies and episode is blocked with the error "Could not find file 'C:\ProgramData\Radarr\bin\UNC\server\AllDebrid magnets\*filename*'"

Changelog "Include source path with Webhook import event movie file" might be the reason 

[rdtclient.log](https://github.com/user-attachments/files/18138175/rdtclient.log)

**Comment by JeroenNieuwenhuis** [comment]
Did you find a solution for this?

**Comment by rogerfar** [comment]
Can you try the latest version and see if that solved it?

**Comment by billouetaudrey** [comment]
> Can you try the latest version and see if that solved it?

On latest version was fixed and suddenly stop working again 😭 any idea ?

**Comment by PandaOAA** [comment]
> Can you try the latest version and see if that solved it?

Still broken after v2.0.96 and latest radarr build (last working with symlinks radarr build is 5.14.0.9383)

**Comment by billouetaudrey** [comment]
> > Can you try the latest version and see if that solved it?
> 
> Still broken after v2.0.96 and latest radarr build (last working with symlinks radarr build is 5.14.0.9383)

Work fine for me

2.0.96 and sonarr 4.0.12.2823

My folder settings /mnt/alldebrid/magnets/*

**Comment by PandaOAA** [comment]
> > > Can you try the latest version and see if that solved it?
> > 
> > 
> > Still broken after v2.0.96 and latest radarr build (last working with symlinks radarr build is 5.14.0.9383)
> 
> Work fine for me
> 
> 2.0.96 and sonarr 4.0.12.2823
> 
> My folder settings /mnt/alldebrid/magnets/*

I use \\server\AllDebrid magnets\* and import fails with this error "Could not find file 'C:\ProgramData\Radarr\bin\UNC\server\AllDebrid magnets\moviename.mkv"

Imports are fine on 5.14.0.9383 and older builds since like a year of updates

Any ideas if I could use a more specific pathname on windows (not docker) for my rclone ?

**Comment by billouetaudrey** [comment]
Do you mount your alldebrid folder on your container (on docker-compose.yml
ou docker run.....)

**Comment by PandaOAA** [comment]
> Do you mount your alldebrid folder on your container (on docker-compose.yml
> ou docker run.....)
> 
> 
> 
> Le sam. 1 févr. 2025, 01:38, PandaOAA ***@***.***> a écrit :
> […](#)

I'm not using docker, my arr apps and rdt-client are run as services/exe

**Comment by billouetaudrey** [comment]
And if you check manually on your folder 
"C:\ProgramData\Radarr\bin\UNC\server\AllDebrid magnets\"
Do you see movie name ?

**Comment by PandaOAA** [comment]
> And if you check manually on your folder "C:\ProgramData\Radarr\bin\UNC\server\AllDebrid magnets" Do you see movie name ?

ok so "\\server\AllDebrid magnets" is my rclone mount and C:\torrents is where symlinks are created before getting moved by radarr/sonarr in my jellyfin folder "C:\Users\Panda\Videos\jellyfin".

This setup works great but since Sonarr 4.0.11.2680 and Radarr 5.15.1.9463 it doesn't work anymore.

"C:\ProgramData\Radarr\bin\UNC\" doesn't exist I think it's an error caused by radarr trying to access network drive instead of the symlink path (btw it can access it without problem as I can access it in the arr apps settings)

**Comment by billouetaudrey** [comment]
I think alldebrid do some change related rclone
Maybe it's your issue 

https://help.alldebrid.com/en/faq/rclone-webdav

rclone.exe mount alldebrid:links X: --dir-cache-time 10s --multi-thread-streams=0 --cutoff-mode=cautious --vfs-cache-mode minimal --network-mode --buffer-size=0 --read-only

**Comment by PandaOAA** [comment]
> I think alldebrid do some change related rclone Maybe it's your issue
> 
> https://help.alldebrid.com/en/faq/rclone-webdav
> 
> rclone.exe mount alldebrid:links X: --dir-cache-time 10s --multi-thread-streams=0 --cutoff-mode=cautious --vfs-cache-mode minimal --network-mode --buffer-size=0 --read-only

Nope it's been mounted with those settings for a year now and never had problems they haven't changed them

My mount is fine it can be accessed from explorer and from rdt-client without any issue

**Comment by billouetaudrey** [comment]
So try to add * at the end of folder settings on rdtclient

And mount the folder on sonarr

Like these screenshots

**Comment by billouetaudrey** [comment]
![Image](https://github.com/user-attachments/assets/c9fd10fc-bfaa-41a0-a164-df5625f4b16b)
![Image](https://github.com/user-attachments/assets/bfd632a9-5222-4fa8-afdc-55600559b85a)

**Comment by billouetaudrey** [comment]
I just try to help you, i had same issue and after all change I tell you
it's working. But maybe it's not exactly same issue

**Comment by PandaOAA** [comment]
> I just try to help you, i had same issue and after all change I tell you
> it's working. But maybe it's not exactly same issue
> 
> Le sam. 1 févr. 2025, 12:45, PandaOAA ***@***.***> a écrit :
> […](#)

rdt-client and radarr are on the same host so symlink folder would be c:/torrents for both remote and local path

I'm glad for the help but ngl my brain is fried trying to fix it

**Comment by Cucumberrbob** [comment]
Couple of notable lines from that log:

```
2024-12-06 04:45:03.788 +01:00 [ERR] RdtClient.Service.BackgroundServices.TaskRunner: Unexpected error occurred in ProviderUpdater: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
...
2024-12-09 21:32:40.209 +01:00 [ERR] RdtClient.Service.BackgroundServices.TaskRunner: Unexpected error occurred in ProviderUpdater: Unable to deserialize AllDebrid API response to MagnetsStatusResponse. Response was: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
...
System.Exception: Unable to deserialize AllDebrid API response to DownloadLink. Response was: Please refresh this page, we have a database error or retry later...
```

That log looks a lot to me like it was AD having some sort of outage. Are you able to upload logs from the latest version?

**Comment by PandaOAA** [comment]
Ok so I just updated to last radarr build to test it (5.19.3.9730) and I'm also using last rdt client build.

![Image](https://github.com/user-attachments/assets/38ef180c-35e4-458b-8b91-3698e727d811)

![Image](https://github.com/user-attachments/assets/373a0651-3d76-46fd-a5ae-377d1332e848)

![Image](https://github.com/user-attachments/assets/11e22d79-6bd7-45b9-9a57-37e442531ece)

![Image](https://github.com/user-attachments/assets/7513a97d-9f7d-456d-bd1c-092f9896838b)

[rdtclient.log](https://github.com/user-attachments/files/19078126/rdtclient.log)

**Comment by Cucumberrbob** [comment]
Sorry I was being dumb in my first comment in this thread, but recent logs are still super helpful!

The problem seems to be that radarr is interpreting the symlinks wrong: it's interpreting the absolute path to the linked file as a relative path somehow (I think). So instead of going to `\\server\AllDebrid magnets`, it goes to `<current working directory for radarr>\server\AllDebrid magnets`.

I'm not sure if this *can* be fixed by `rdt-client`, given that the problem isn't finding the file, the problem is with following the symlink.

Unless the symlinks are being created wrong...
Could you post the output of running this in a powershell window? (change `C:\path\to\symlink` for the actual path)
```posh
(Get-Item "C:\path\to\symlink").Target
```
That should output the path the symlink points to.

**Comment by PandaOAA** [comment]
> Sorry I was being dumb in my first comment in this thread, but recent logs are still super helpful!
> 
> The problem seems to be that radarr is interpreting the symlinks wrong: it's interpreting the absolute path to the linked file as a relative path somehow (I think). So instead of going to `\\server\AllDebrid magnets`, it goes to `<current working directory for radarr>\server\AllDebrid magnets`.
> 
> I'm not sure if this _can_ be fixed by `rdt-client`, given that the problem isn't finding the file, the problem is with following the symlink. (also that old versions of `radarr` do work by the sounds of it, but old versions of `rdt-client` don't)
> 
> Unless the symlinks are being created wrong... Could you post the output of running this in a powershell window? (change `C:\path\to\symlink` for the actual path)
> 
> (Get-Item "C:\path\to\symlink").Target
> Then open a new powershell window in a different folder and do it again. That should tell us if it actually _is_ a relative path somehow.

I tested on a movie and it showed "UNC\server\AllDebrid magnets\Venom.The.Last.Dance.2024.MULTi.TRUEFRENCH.2160p.HDR.DV.WEB-DL.H265-Slay3R.mkv"

**Comment by PandaOAA** [comment]
> Sorry I was being dumb in my first comment in this thread, but recent logs are still super helpful!
> 
> The problem seems to be that radarr is interpreting the symlinks wrong: it's interpreting the absolute path to the linked file as a relative path somehow (I think). So instead of going to `\\server\AllDebrid magnets`, it goes to `<current working directory for radarr>\server\AllDebrid magnets`.
> 
> I'm not sure if this _can_ be fixed by `rdt-client`, given that the problem isn't finding the file, the problem is with following the symlink. (also that old versions of `radarr` do work by the sounds of it, but old versions of `rdt-client` don't)
> 
> Unless the symlinks are being created wrong... Could you post the output of running this in a powershell window? (change `C:\path\to\symlink` for the actual path)
> 
> (Get-Item "C:\path\to\symlink").Target
> Then open a new powershell window in a different folder and do it again. That should tell us if it actually _is_ a relative path somehow.

After testing, only radarr build really matters. Every rdt-client builds tested works with radarr builds under 5.15.1.9463
